name: oru_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  get_cli: any
  get: 4.6.5
  flutter: 
    sdk: flutter
  carousel_slider: ^4.2.1
  http:
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  intl: ^0.17.0 
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^8.2.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  smooth_page_indicator: ^1.1.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/brandlogo/
    - assets/images/slider_Image/

